# Generated by Django 4.2.19 on 2025-03-15 19:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название баннера.')),
                ('redirect_url', models.URLField(blank=True, default=None, null=True, verbose_name='Переход по клику.')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение баннера.')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Позиция баннера.')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации.')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления.')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
