# Generated by Django 4.2.19 on 2025-03-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_banner_date_published_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='BannerModel',
        ),
    ]
