# Generated by Django 4.2.19 on 2025-03-16 16:31

from django.db import migrations, models
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_banner_bannermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(upload_to='static/banners', verbose_name='Изображение баннера.'),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='position',
            field=positions.fields.PositionField(default=-1, verbose_name='Позиция баннера.'),
        ),
    ]
