# Generated by Django 4.2.19 on 2025-03-17 21:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bannermodel_image_alter_bannermodel_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='Имя.')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
