# Generated by Django 4.2.19 on 2025-03-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedbackrequestmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackrequestmodel',
            options={'verbose_name': 'Заказ звонка', 'verbose_name_plural': 'Заказы звонков'},
        ),
    ]
