# Generated by Django 4.2.19 on 2025-03-15 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название Производителя.')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название категории.')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название модели.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brandmodel', verbose_name='Производитель.')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='AutomobileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание товара.')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], verbose_name='Год выпуска.')),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег.')),
                ('color', models.CharField(max_length=256, verbose_name='Цвет.')),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мощность.')),
                ('drive', models.CharField(choices=[('FWD', 'Передний Привод'), ('AWD', 'Полный Привод'), ('RWD', 'Задний Привод')], max_length=3, verbose_name='Привод.')),
                ('body', models.CharField(choices=[('SEDAN', 'Седан'), ('COUPE', 'Купе'), ('HATCHBACK', 'Хетчбэк'), ('LIFTBACK', 'Лифтбэк'), ('FASTBACK', 'Фастбэк'), ('UNIVERSAL', 'Универсал'), ('CROSSOVER', 'Кроссовер'), ('OFFROAD', 'Внедорожник'), ('PICKUP', 'Пикап'), ('LIGHTVAN', 'Легковой фургон'), ('MINIVAN', 'Минивен'), ('COMPACTVAN', 'Компактвен'), ('MICROVAN', 'Микровен'), ('CABRIO', 'Кабриолет'), ('ROADSTER', 'Родстер'), ('TARGA', 'Тарга'), ('LANDO', 'Ландо'), ('LIMOUSINE', 'Лимузин'), ('TRUCK', 'Тягач')], max_length=128, verbose_name='Кузов.')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Страна.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Цена.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.brandmodel', verbose_name='Производитель.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.categorymodel', verbose_name='Категория.')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.modelmodel', verbose_name='Модель.')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
