# Generated by Django 4.2.19 on 2025-03-15 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение.')),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Позиция.')),
            ],
            options={
                'verbose_name': 'Изображение автомобиля',
                'verbose_name_plural': 'Изображения автомобиля',
            },
        ),
        migrations.AddField(
            model_name='automobilemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='automobilemodel',
            name='used',
            field=models.BooleanField(default=False, verbose_name='БУ.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='automobilemodel',
            name='category',
            field=models.CharField(choices=[('AUTO', 'Автомобиль'), ('TRUCK', 'Грузовик')], max_length=256, verbose_name='Категория.'),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.AddField(
            model_name='automobileimage',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.automobilemodel', verbose_name='Автомобиль.'),
        ),
    ]
