# Generated by Django 4.2.19 on 2025-03-15 21:49

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_automobileimage_automobilemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobileimage',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
