# Generated by Django 4.2.19 on 2025-03-15 22:20

from django.db import migrations, models
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_automobileimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobileimage',
            name='image',
            field=models.ImageField(upload_to='static/images/auto', verbose_name='Изображение.'),
        ),
        migrations.AlterField(
            model_name='automobileimage',
            name='position',
            field=positions.fields.PositionField(default=-1, verbose_name='Позиция.'),
        ),
    ]
