# Generated by Django 4.2.19 on 2025-03-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_automobileimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilemodel',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Зарезервировано.'),
        ),
        migrations.AddField(
            model_name='automobilemodel',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продано.'),
        ),
        migrations.AlterField(
            model_name='automobileimage',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.automobilemodel', verbose_name='Автомобиль.'),
        ),
    ]
