# Generated by Django 4.2.19 on 2025-03-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='grade',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='newsletter',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подписка на рассылку'),
        ),
    ]
