# Generated by Django 4.2.19 on 2025-03-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedbackmodel_grade_feedbackmodel_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='wishes',
            field=models.TextField(blank=True, null=True, verbose_name='Пожелания к сайту'),
        ),
    ]
